// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbAyNFIO9VdildlK4bkuoqkeEa67x7E4',
    appId: '1:638583943713:web:287c269c4e7236e090a960',
    messagingSenderId: '638583943713',
    projectId: 'zing---couple-virtual-space',
    authDomain: 'zing---couple-virtual-space.firebaseapp.com',
    storageBucket: 'zing---couple-virtual-space.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jmeU_MssbGt89LAPxvrzf0gRguTrbC4',
    appId: '1:638583943713:android:a800cbb3b0bc1a6890a960',
    messagingSenderId: '638583943713',
    projectId: 'zing---couple-virtual-space',
    storageBucket: 'zing---couple-virtual-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdp50J7iTkUeG_O7yAGTAVAYOfOglB-A',
    appId: '1:638583943713:ios:475fd72e5e9d5d9890a960',
    messagingSenderId: '638583943713',
    projectId: 'zing---couple-virtual-space',
    storageBucket: 'zing---couple-virtual-space.firebasestorage.app',
    iosClientId: '638583943713-71900jhg5oa2sq69fcasr82f627suc53.apps.googleusercontent.com',
    iosBundleId: 'com.example.zing',
  );
}
